version: "3.7"
services:
  progresql:
    image: postgres:latest
    container_name: postgresql
    networks:
      - default
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=BoardGame
